# Generated by Django 6.0 on 2025-12-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_fa', models.CharField(max_length=200, verbose_name='Title (Persian)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fa', models.TextField(verbose_name='Description (Persian)')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_fa', models.CharField(max_length=200, verbose_name='Title (Persian)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_fa', models.TextField(blank=True, verbose_name='Description (Persian)')),
                ('slug', models.SlugField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_fa', models.CharField(max_length=200, verbose_name='Title (Persian)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_fa', models.TextField(verbose_name='Content (Persian)')),
                ('code_example', models.TextField(blank=True, verbose_name='Code Example')),
                ('code_example_windows', models.TextField(blank=True, verbose_name='Windows Code Example')),
                ('code_example_mac', models.TextField(blank=True, verbose_name='Mac Code Example')),
                ('exercise_en', models.TextField(blank=True, verbose_name='Exercise (English)')),
                ('exercise_fa', models.TextField(blank=True, verbose_name='Exercise (Persian)')),
                ('exercise_solution', models.TextField(blank=True, verbose_name='Exercise Solution')),
                ('slug', models.SlugField()),
                ('order', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('code', 'Code Example'), ('exercise', 'Exercise')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
