"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# Development-only fallback (only used if DEBUG=True)
if SECRET_KEY is None:
    # DEBUG flag will be set next, default to True for development
    if os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes'):
        # Development default - DO NOT use in production
        SECRET_KEY = 'django-insecure-dev-key-change-me-in-production'
        import warnings
        warnings.warn(
            "Using default SECRET_KEY. Set SECRET_KEY environment variable for production!",
            RuntimeWarning,
            stacklevel=2
        )
    else:
        raise ValueError(
            "SECRET_KEY environment variable must be set in production. "
            "DEBUG is False but SECRET_KEY is not configured."
        )

# SECURITY WARNING: don't run with debug turned on in production!
# For development: DEBUG defaults to True
# For production: Explicitly set DEBUG=False in environment
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Add helpful development reminder
if DEBUG:
    import warnings
    warnings.warn(
        "Running in DEBUG mode. Set DEBUG=False for production!",
        RuntimeWarning,
        stacklevel=2
    )

# ALLOWED_HOSTS configuration
# Development: Allow localhost and 127.0.0.1
# Production: Set ALLOWED_HOSTS environment variable with comma-separated domains
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    # In production, ALLOWED_HOSTS must be explicitly set
    allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '')
    if not allowed_hosts_str:
        raise ValueError(
            "ALLOWED_HOSTS environment variable must be set in production. "
            "Example: ALLOWED_HOSTS=example.com,www.example.com"
        )
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]

# Gemini API Keys - Support multiple keys for fallback and high availability
GEMINI_API_KEYS = [
    os.environ.get('GEMINI_API_KEY', ''),
    os.environ.get('GEMINI_API_KEY_2', ''),
]
# Filter out empty keys
GEMINI_API_KEYS = [key for key in GEMINI_API_KEYS if key]

# For backward compatibility, keep single key support
GEMINI_API_KEY = GEMINI_API_KEYS[0] if GEMINI_API_KEYS else ''


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses',
    'ai_assistant',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LanguageMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('fa', 'Persian'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if DEBUG else []

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
